# Generated by Django 4.0.5 on 2022-08-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0002_alter_user_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=32, verbose_name='标签')),
                ('unm', models.CharField(max_length=32, verbose_name='账号')),
                ('pwd', models.CharField(max_length=32, verbose_name='密码')),
                ('tsp', models.CharField(max_length=8, verbose_name='时间戳')),
            ],
        ),
    ]
