# Generated by Django 4.1.2 on 2022-11-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0007_alter_memorandum_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorandum',
            name='status',
            field=models.BooleanField(default=False, verbose_name='状态'),
        ),
    ]
