# Generated by Django 4.0.5 on 2022-08-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0004_alter_codebook_tsp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memorandum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64, null=True, verbose_name='标题')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('timeStamp', models.DateField(verbose_name='时间戳')),
            ],
        ),
    ]
