# Generated by Django 4.1.2 on 2023-04-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0009_notebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codebook',
            name='pwd',
            field=models.CharField(max_length=32, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='codebook',
            name='tag',
            field=models.CharField(max_length=32, verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='codebook',
            name='tsp',
            field=models.DateField(verbose_name='TimeStamp'),
        ),
        migrations.AlterField(
            model_name='codebook',
            name='unm',
            field=models.CharField(max_length=32, verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='memorandum',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='memorandum',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='memorandum',
            name='timeStamp',
            field=models.DateTimeField(verbose_name='TimeStamp'),
        ),
        migrations.AlterField(
            model_name='memorandum',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='head',
            field=models.CharField(max_length=64, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='timeStamp',
            field=models.DateTimeField(verbose_name='TimeStamp'),
        ),
    ]
