# Generated by Django 4.1.2 on 2022-11-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0008_alter_memorandum_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=64, verbose_name='标题')),
                ('body', models.TextField(blank=True, null=True, verbose_name='正文')),
                ('timeStamp', models.DateTimeField(verbose_name='创建时间')),
            ],
        ),
    ]
